language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t baasvancodeza/react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true baasvancodeza/react-client-test npm run test

after_succes:
  - docker build -t baasvancodeza/multi-cleint ./client
  - docker build -t baasvancodeza/multi-server ./server
  - docker build -t baasvancodeza/multi-nginx ./nginx
  - docker build -t baasvancodeza/multi-worker ./worker
  # Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to dockerhub
  - docker push baasvancodeza/multi-cleint
  - docker push baasvancodeza/multi-server
  - docker push baasvancodeza/multi-nginx
  - docker push baasvancodeza/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-211332116103"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KE
